#!/bin/sh

stty -F /dev/ttyACM0 cs8 9600 ignbrk -brkint -icrnl -imaxbel -opost -onlcr -isig -icanon -iexten -echo -echoe -echok -echoctl -echoke noflsh -ixon -crtscts -hupcl

echo "?P9 P?P8 P2?P7 P3?P6 P4?P5      P5?P4 P6?P3 P7?P2 P8?P P9?" >/dev/ttyACM0
