#!/bin/sh

stty -F /dev/ttyACM0 cs8 9600 ignbrk -brkint -icrnl -imaxbel -opost -onlcr -isig -icanon -iexten -echo -echoe -echok -echoctl -echoke noflsh -ixon -crtscts -hupcl

echo "?p9 p?p8 p2?p7 p3?p6 p4?p5      p5?p4 p6?p3 p7?p2 p8?p p9?" >/dev/ttyACM0
